import {NextResponse, type NextRequest} from 'next/server';
import {createClient} from '@/lib/supabase/server';
import {routing} from '@/i18n/routing';

/**
 * Email-confirmation landing. Supabase redirects here with a one-time `code`
 * which must be exchanged for a session server-side.
 *
 * Outside the [locale] segment on purpose: the confirmation link is generated by
 * Supabase and cannot carry our locale prefix, so we resolve the locale from the
 * `next` param (or fall back to the default) and redirect into the localised app.
 */
export async function GET(request: NextRequest) {
  const {searchParams, origin} = new URL(request.url);
  const code = searchParams.get('code');
  const next = searchParams.get('next');

  const locale =
    next && (routing.locales as readonly string[]).includes(next.split('/')[1] ?? '')
      ? next.split('/')[1]
      : routing.defaultLocale;

  if (!code) {
    return NextResponse.redirect(`${origin}/${locale}/login`);
  }

  const supabase = await createClient();
  const {error} = await supabase.auth.exchangeCodeForSession(code);

  if (error) {
    return NextResponse.redirect(`${origin}/${locale}/login`);
  }

  return NextResponse.redirect(`${origin}/${locale}/me/applications`);
}
